### PR TITLE
New Design for events.apache.org

### PR DESCRIPTION
**Pull request by RedYetiDev**
In <https://events.apache.org/about/commcode/volunteer.html>, the following item was listed: 'Keep this events.apache.org [website source code updated](https://svn.apache.org/repos/asf/concom/site/trunk/content). Possibly make it look better.', so I took on the task.

This Pull-Request completely redesigns the website. It's hard to list all the changes, but I'll try
## Technical
- Remove `.htaccess` and update links directly
- Remove `/x/`, as it always redirects to Community Over Code
- Remove extra unused images
- Make outgoing links target `_blank`
- Update copyrights
- Edit README.md for the newer site

## Layouts + CSS
- Replace the navbar with a expanding sidebar
- Redo the CSS stylings in accordance with the changes to the website
- Add a 404 page

## Homepage
- Remove event listing
- Rewrite introduction + Table of Contents

## Events
- Replace 'past events' and 'upcoming events' with a calendar
- Switch from native google calendar to fullcalendar
- Retype introduction to calendar

## About
- Added 'The current version of this site was designed by [Aviv Keller (@RedYetiDev)](https://github.com/redyetidev)' to 'About This Website' (Credit where credit is due)
- Replace 'apachecon' (404) link with 'Community Over Code'
- Fix duplicated title in 'Endorsed Events'

## Community For Code / ApacheCon
- Fix invalid markdown
- Reorganize list
- Remove 'Possibly make it look better.' from volunteer opportunities
- Fix incorrect twitter URLs

## Getting Involved
- Add subheaders to introduction
- Redesign Mailing List Table

## Screenshots
image
image
image

### CODE REVIEW

**Comment by bdelacretaz** [comment]
This changes many things indeed, in general we prefer having "atomic" PRs which change one thing only and can be reviewed in isolation. I suggest creating separate PRs at least for the content changes vs style/behavior/navigation changes, to make the review easier.

**Comment by RedYetiDev** [comment]
Okay! Do you want me to split up this PR, or keep that in note for the future?

Thank you!

**Comment by RedYetiDev** [comment]
Hey, @bdelacretaz, would you like me to close this and open more similar to #13, or close #13 in favor this (#12)?

**Comment by bdelacretaz** [comment]
#13 looks focused on style + nav changes which is good, in terms of being "a single thing". Best might be to close this PR and create another one with the suggested content changes, assuming they are "a single thing", or several PRs if they have distinct goals.

**Comment by RedYetiDev** [comment]
Sounds good!

**Pull request closed without merging**
